export enum TaskType {
  TASK = 'TASK',
  SUB_TASK = 'SUB_TASK',
}

export enum TaskStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  REVIEW = 'REVIEW',
  DONE = 'DONE',
}

export enum TaskPriority {
  LOWEST = 'LOWEST',
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  HIGHEST = 'HIGHEST',
}

export enum WorkspaceRole {
  OWNER = 'OWNER',
  MEMBER = 'MEMBER',
  GUEST = 'GUEST',
}

export enum ErrorCode {
  // Auth errors (AUTH_xxx)
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_USER_DELETED = 'AUTH_USER_DELETED',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_RESET_TOKEN_EXPIRED = 'AUTH_RESET_TOKEN_EXPIRED',
  AUTH_RESET_TOKEN_INVALID = 'AUTH_RESET_TOKEN_INVALID',
  AUTH_PASSWORD_WEAK = 'AUTH_PASSWORD_WEAK',

  // Validation errors (VALIDATION_xxx)
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  VALIDATION_EMAIL_INVALID = 'VALIDATION_EMAIL_INVALID',
  VALIDATION_PASSWORD_WEAK = 'VALIDATION_PASSWORD_WEAK',
  VALIDATION_REQUIRED_FIELD = 'VALIDATION_REQUIRED_FIELD',

  // User errors (USER_xxx)
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',
  USER_DELETED = 'USER_DELETED',

  // Workspace errors (WORKSPACE_xxx)
  WORKSPACE_NOT_FOUND = 'WORKSPACE_NOT_FOUND',
  WORKSPACE_NAME_REQUIRED = 'WORKSPACE_NAME_REQUIRED',
  WORKSPACE_NAME_TOO_LONG = 'WORKSPACE_NAME_TOO_LONG',
  WORKSPACE_DELETE_FORBIDDEN = 'WORKSPACE_DELETE_FORBIDDEN',
  WORKSPACE_LEAVE_FORBIDDEN = 'WORKSPACE_LEAVE_FORBIDDEN',
  WORKSPACE_CANNOT_REMOVE_OWNER = 'WORKSPACE_CANNOT_REMOVE_OWNER',

  // WorkspaceMember errors (MEMBER_xxx)
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
  MEMBER_ALREADY_EXISTS = 'MEMBER_ALREADY_EXISTS',
  MEMBER_CANNOT_CHANGE_OWNER_ROLE = 'MEMBER_CANNOT_CHANGE_OWNER_ROLE',
  MEMBER_CANNOT_REMOVE_SELF = 'MEMBER_CANNOT_REMOVE_SELF',

  // Invitation errors (INVITATION_xxx)
  INVITATION_NOT_FOUND = 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED = 'INVITATION_EXPIRED',
  INVITATION_ALREADY_ACCEPTED = 'INVITATION_ALREADY_ACCEPTED',
  INVITATION_ALREADY_DECLINED = 'INVITATION_ALREADY_DECLINED',

  // Project errors (PROJECT_xxx)
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  PROJECT_KEY_REQUIRED = 'PROJECT_KEY_REQUIRED',
  PROJECT_KEY_EXISTS = 'PROJECT_KEY_EXISTS',
  PROJECT_NAME_REQUIRED = 'PROJECT_NAME_REQUIRED',
  PROJECT_NAME_TOO_LONG = 'PROJECT_NAME_TOO_LONG',

  // Task errors (TASK_xxx)
  TASK_NOT_FOUND = 'TASK_NOT_FOUND',
  TASK_TITLE_REQUIRED = 'TASK_TITLE_REQUIRED',
  TASK_TITLE_TOO_LONG = 'TASK_TITLE_TOO_LONG',
  TASK_PARENT_NOT_FOUND = 'TASK_PARENT_NOT_FOUND',
  TASK_CANNOT_BE_OWN_SUBTASK = 'TASK_CANNOT_BE_OWN_SUBTASK',
  TASK_SUBTASK_LIMIT_EXCEEDED = 'TASK_SUBTASK_LIMIT_EXCEEDED',

  // Comment errors (COMMENT_xxx)
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
  COMMENT_CONTENT_REQUIRED = 'COMMENT_CONTENT_REQUIRED',

  // Attachment errors (ATTACHMENT_xxx)
  ATTACHMENT_NOT_FOUND = 'ATTACHMENT_NOT_FOUND',
  ATTACHMENT_UPLOAD_FAILED = 'ATTACHMENT_UPLOAD_FAILED',
  ATTACHMENT_FILE_TOO_LARGE = 'ATTACHMENT_FILE_TOO_LARGE',
  ATTACHMENT_INVALID_TYPE = 'ATTACHMENT_INVALID_TYPE',

  // Notification errors (NOTIFICATION_xxx)
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',

  // Permission errors (FORBIDDEN_xxx)
  FORBIDDEN_ACCESS = 'FORBIDDEN_ACCESS',
  FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE',

  // General errors (INTERNAL_xxx)
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
}

export enum NotificationType {
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_COMMENTED = 'TASK_COMMENTED',
  TASK_COMPLETED = 'TASK_COMPLETED',
  MEMBER_JOINED = 'MEMBER_JOINED',
  INVITATION_RECEIVED = 'INVITATION_RECEIVED',
}

export enum InvitationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  EXPIRED = 'EXPIRED',
}

export enum ActivityAction {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  DELETED = 'DELETED',
  ASSIGNED = 'ASSIGNED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  PRIORITY_CHANGED = 'PRIORITY_CHANGED',
  COMMENTED = 'COMMENTED',
  ATTACHMENT_ADDED = 'ATTACHMENT_ADDED',
  MEMBER_ADDED = 'MEMBER_ADDED',
  MEMBER_REMOVED = 'MEMBER_REMOVED',
}
